add readr::problems() to namespace
frictionlessdata/frictionless-r pull request #131
Opened 2023-03-22 07:55 UTC by PietrH

Resolves #129 

For future reference:

```r 
usethis::use_package_doc(open = rlang::is_interactive())
usethis::use_import_from("readr","problems")
devtools::document()
```

2023-03-22 08:07 UTC, PietrH commented
ready for review

2023-03-23 09:01 UTC, peterdesmet requested changes
When I install this package, I try ` problems(df)` I get:

> Error in problems(df) : could not find function "problems"

2023-03-23 09:31 UTC, PietrH commented
It helps to actually export functions instead of just adding them to the namespace, should be fixed now.

2023-03-23 09:37 UTC, peterdesmet commented
What command did you use to export it?

Also, we now get:

```
❯ checking for missing documentation entries ... WARNING
  Undocumented code objects:
    'problems'
  All user-level objects in a package should have documentation entries.
  See chapter 'Writing R documentation files' in the 'Writing R
  Extensions' manual.
```

2023-03-23 09:44 UTC, PietrH commented
`usethis::use_import_from()` followed by adding the export manually, I didn't run R CMD CHECK but clearly should have! 

I'm getting the idea this is not the best way to do this. Let me reevaluate and I'll let you know when I'm ready to revisit this review.

2023-03-24 15:49 UTC, PietrH commented
I've changed the implementation to use a `utils-*.R` script that only imports the namespace, and exports the function from readr. I've copied this mostly from how `usethis::use_pipe() `does it for `magrittr:::\\>%\\%`

The documentation just refers to readr, is this sufficient? It does pass `devtools::check()`

2023-03-24 17:46 UTC, peterdesmet approved these changes

2023-03-24 18:23 UTC, peterdesmet commented on R/utils-problems.R
> +#' @noRd
@PietrH I was wrong. Not creating an `rd` will result in a CHECK warning. Fixed in 861d808. The "Help on topic 'problems' was found in the following packages:" is thus unavoidable.

2023-03-27 08:18 UTC, merged