Allow to add resource from csv file(s) in `add_resource()`
frictionlessdata/frictionless-r pull request #76
Opened 2022-01-07 22:00 UTC by peterdesmet

Fixes #74

- Allows a resource to be **added from file path(s)** rather than a data frame. The same parameter `data` is used to attach data frames or file path(s).
- Function will internally use the last provided file to make a `df`. This `df` is necessary to create or compare with a `schema`.
  - Only one file is read to speed up the process (otherwise why add csv's directly?).
  - The last file is used, since for growing datasets that is likely going to be the newest (and not yet checked) one.
  - The default `read_delim(delim = ",", progress = FALSE, show_col_types = FALSE)` behaviour can be overwritten by the user by providing more arguments in `...`
- Provided paths can be absolute or relative, since they are set by the user (and not unsafe). A new `attr` is added to the resource so that `get_resource()` does check for unsafe paths for these resources.
- The new use of the function is shown in the example and vignette.

Also includes:
- Renames `df` parameter to `data` in `create_schema()` and internal `check_schema()` as well.
- No longer refer to `df` in error messages, use `data` or data.
- Rename internal `list_clean()` to `clean_list()` (verb first).

No additional test have been added, so coverage is likely to drop. Will be added before PR can be accepted.

2022-01-10 13:39 UTC, damianooldoni approved these changes
It seems everything is fine. I have mainly provided feedback related to the documentation. See comments.

2022-01-10 13:39 UTC, damianooldoni commented on R/add_resource.R
> +#'   - Path(s) to CSV file(s): added to the resource as `path`.
I would add the fact that paths should be passed as a vector. Or do you want to support lists as well? I think a vector with paths is sufficient. But, it should be mentioned in documentation.

2022-01-10 13:39 UTC, damianooldoni commented on R/add_resource.R
> +#' # Add a new resource "deployments2" to the Data Package, from a CSV file path
I think it would be worth to add the following examples:
1. multiple paths
2. user passes a schema via arg `schema`

2022-01-10 13:39 UTC, damianooldoni commented on R/add_resource.R
> +    read_args$progress <- replace_null(read_args$progress, FALSE)
Personally I like to show always progress bars when reading files. The reason is quite simple. 
If the file is small, you don't notice the bar even and the processing time is still very small. If the file is big, you know why you are waiting for.

2022-01-12 14:50 UTC, damianooldoni requested changes
Yes, #77 was indeed tricky. At the end writing to disk is unavoidable.

Could you please add some message to inform the user about the progress of `write_package()`? Based on your example in #77 it seems that it can take up to minutes to download everything and you know how annoying it can be to not receive any information about the status of a function running for more than few seconds 😄 
As reference example, I have in mind the first part of the message returned by `etn::download_acoustic_dataset()`, see lines [L55-L63](https://github.com/inbo/etn/blob/main/R/download_acoustic_dataset.R#L55-L63).

2022-01-12 16:47 UTC, peterdesmet commented
@damianooldoni Download function will now display a message (4c2d1b4):

```R
> write_package(package, "zenodo")
Downloading file from https://zenodo.org/record/5070086/files/O_WESTERSCHELDE-acceleration-2019.csv
Downloading file from https://zenodo.org/record/5070086/files/O_WESTERSCHELDE-acceleration-2020.csv
```

2022-01-12 20:00 UTC, damianooldoni approved these changes
Nice work, @peterdesmet!

2022-01-12 20:02 UTC, merged